### ISSUE TITLE
Build Failure - Missing file bin/compile-forms.py

### ISSUE THREAD

**Issue by gihyunlee** [Alfresco/activiti-contract-mgmt-sample#1]
I am getting the following build failure when running the build

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (compile-forms) on project case-mgmt-sample: Command execution failed. Cannot run program "bin/compile-forms.py" (in directory "/Developer/code/activiti/activiti-contract-mgmt-sample"): error=2, No such file or directory -> [Help 1]

The file compile-forms.py is not available in source.

**Comment by wabson** [comment]
Thanks for reporting this Gi, hopefully it works for you now
